/**
 * 교육과정 단원 시드 데이터 — 초1~고3 전 학년 통합 (T0.3)
 *
 * 원본(읽기 전용 이관 소스, 절대 수정 금지):
 *   C:\Creative\eywa\src\features\onescreen\curriculum.ts (MATH_CURRICULUM)
 *   — 학원 관리 시스템 eywa가 실운영 중인 "진도 피커" 데이터. 차시 단위까지 손검증되어 있어
 *     기존 3개 후보 소스(mathlab/math-report/math_test 조합안)보다 신뢰도가 높아 이 소스로 전환했다
 *     (오케스트레이터 지시 — 2026-08-13). 참고: eywa의 curriculum-position.ts, curriculum.test.ts.
 *
 * 매핑 규칙:
 *   - grade   : 초1~중3은 eywa 원본 학년 키를 그대로 사용(이미 "초1".."중3" 형식).
 *               고등은 과목명을 grade로 사용하되 로마자 학년 표기를 아라비아 숫자로 변환
 *               ("미적분Ⅰ" → "미적분1", "미적분Ⅱ" → "미적분2") — VarChar(10) 확인, 최대 6자("확률과 통계").
 *   - chapter : 원본 단원(unit) 문자열 그대로(번호 접두 포함, 손검증 데이터 보존 — 임의 가공 금지).
 *   - section : 원본 차시(lesson) 문자열 그대로 — 진도 입력의 실제 단위.
 *   - orderIndex : 전역 연속값(1부터, D-27). 초1→중3은 eywa curriculum.ts 정의 순서(그 자체가 진도
 *     타임라인 — curriculum-position.ts 주석 "학년 순서가 곧 진도 타임라인" 참조), 그 뒤 고등 7과목은
 *     "공통수학1 → 공통수학2 → 대수 → 미적분1 → 확률과 통계 → 기하 → 미적분2" 순으로 고정 이어 붙인다.
 *
 * ⚠️ 고등 과목 순서 결정 근거 (원장님 확인 필요):
 *   오케스트레이터 지시문은 "공통수학1→공통수학2→대수→미적분1→확률과통계→기하" 6개 과목만 나열하고
 *   미적분Ⅱ(미적분2)를 언급하지 않았다. 그러나 eywa 원본에는 실제로 고등 7과목(공통수학1·2, 대수,
 *   미적분Ⅰ·Ⅱ, 확률과 통계, 기하)이 정의되어 있고 동봉된 curriculum.test.ts도 이 7개를 모두 검증한다.
 *   데이터 손실을 피하기 위해 미적분2를 포함시켰고, 위치는 오케스트레이터가 준 접두 순서를 그대로 둔 채
 *   eywa 원본 정의 순서와 동일하게 맨 끝(기하 다음)에 이어 붙였다. eywa 자체는 고등 과목을 진도
 *   전역 타임라인에서 제외하므로(과목 선택제 + 차시명 중복) 이 순서가 실서비스 동작에 영향을 주지 않는
 *   보수적 선택이다 — 원장님 검수 시 순서 재조정 가능.
 *
 * orderIndex는 아래 배열 조립 순서(=이 파일의 서술 순서)로부터 스크립트로 부여했다(수기 번호 아님 —
 * prisma/seed.ts 및 단위 테스트가 이 배열의 인덱스 연속성을 그대로 검증한다).
 */

export interface UnitSeed {
  /** 학년(초1~중3) 또는 고등 과목명 — DB VarChar(10) */
  grade: string;
  /** 대단원 — DB VarChar(100) */
  chapter: string;
  /** 소단원(차시) — DB VarChar(100) */
  section: string;
  /** 전역 연속 순서값 (1-based) — D-27 */
  orderIndex: number;
}

export const CURRICULUM_UNITS: UnitSeed[] = [
  // ═════════ 초1 ═════════
  // ── 1-1 9까지의 수 ──
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-1 1부터 5까지의 수 알아보기",
    orderIndex: 1,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-2 6부터 9까지의 수 알아보기",
    orderIndex: 2,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-3 몇째인지 알아보기",
    orderIndex: 3,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-4 수의 순서 알아보기",
    orderIndex: 4,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-5 1만큼 더 큰 수와 1만큼 더 작은 수",
    orderIndex: 5,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-6 0 알아보기",
    orderIndex: 6,
  },
  {
    grade: "초1",
    chapter: "1-1 9까지의 수",
    section: "1-1-7 9까지 수의 크기 비교",
    orderIndex: 7,
  },
  // ── 1-2 여러 가지 모양 ──
  {
    grade: "초1",
    chapter: "1-2 여러 가지 모양",
    section: "1-2-1 여러 가지 모양 찾아보기",
    orderIndex: 8,
  },
  {
    grade: "초1",
    chapter: "1-2 여러 가지 모양",
    section: "1-2-2 여러 가지 모양 알아보기",
    orderIndex: 9,
  },
  {
    grade: "초1",
    chapter: "1-2 여러 가지 모양",
    section: "1-2-3 여러 가지 모양으로 만들기",
    orderIndex: 10,
  },
  // ── 1-3 덧셈과 뺄셈 ──
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-1 모으기와 가르기",
    orderIndex: 11,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-2 덧셈식으로 나타내기",
    orderIndex: 12,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-3 덧셈하기",
    orderIndex: 13,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-4 뺄셈식으로 나타내기",
    orderIndex: 14,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-5 뺄셈하기",
    orderIndex: 15,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-6 0이 있는 덧셈과 뺄셈",
    orderIndex: 16,
  },
  {
    grade: "초1",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-7 덧셈과 뺄셈하기",
    orderIndex: 17,
  },
  // ── 1-4 비교하기 ──
  {
    grade: "초1",
    chapter: "1-4 비교하기",
    section: "1-4-1 길이 비교하기",
    orderIndex: 18,
  },
  {
    grade: "초1",
    chapter: "1-4 비교하기",
    section: "1-4-2 무게 비교하기",
    orderIndex: 19,
  },
  {
    grade: "초1",
    chapter: "1-4 비교하기",
    section: "1-4-3 넓이 비교하기",
    orderIndex: 20,
  },
  {
    grade: "초1",
    chapter: "1-4 비교하기",
    section: "1-4-4 담을 수 있는 양 비교하기",
    orderIndex: 21,
  },
  // ── 1-5 50까지의 수 ──
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-1 10 알아보기",
    orderIndex: 22,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-2 십몇 알아보기",
    orderIndex: 23,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-3 십몇의 모으기와 가르기",
    orderIndex: 24,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-4 10개씩 묶어 세기",
    orderIndex: 25,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-5 50까지의 수 세기",
    orderIndex: 26,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-6 50까지 수의 순서",
    orderIndex: 27,
  },
  {
    grade: "초1",
    chapter: "1-5 50까지의 수",
    section: "1-5-7 50까지 수의 크기 비교",
    orderIndex: 28,
  },
  // ── 2-1 100까지의 수 ──
  {
    grade: "초1",
    chapter: "2-1 100까지의 수",
    section: "2-1-1 60, 70, 80, 90 알아보기",
    orderIndex: 29,
  },
  {
    grade: "초1",
    chapter: "2-1 100까지의 수",
    section: "2-1-2 99까지의 수 알아보기",
    orderIndex: 30,
  },
  {
    grade: "초1",
    chapter: "2-1 100까지의 수",
    section: "2-1-3 100까지 수의 순서",
    orderIndex: 31,
  },
  {
    grade: "초1",
    chapter: "2-1 100까지의 수",
    section: "2-1-4 100까지 수의 크기 비교",
    orderIndex: 32,
  },
  {
    grade: "초1",
    chapter: "2-1 100까지의 수",
    section: "2-1-5 짝수와 홀수",
    orderIndex: 33,
  },
  // ── 2-2 덧셈과 뺄셈(1) ──
  {
    grade: "초1",
    chapter: "2-2 덧셈과 뺄셈(1)",
    section: "2-2-1 세 수의 덧셈",
    orderIndex: 34,
  },
  {
    grade: "초1",
    chapter: "2-2 덧셈과 뺄셈(1)",
    section: "2-2-2 세 수의 뺄셈",
    orderIndex: 35,
  },
  {
    grade: "초1",
    chapter: "2-2 덧셈과 뺄셈(1)",
    section: "2-2-3 10이 되는 더하기",
    orderIndex: 36,
  },
  {
    grade: "초1",
    chapter: "2-2 덧셈과 뺄셈(1)",
    section: "2-2-4 10에서 빼기",
    orderIndex: 37,
  },
  {
    grade: "초1",
    chapter: "2-2 덧셈과 뺄셈(1)",
    section: "2-2-5 10을 만들어 더하기",
    orderIndex: 38,
  },
  // ── 2-3 모양과 시각 ──
  {
    grade: "초1",
    chapter: "2-3 모양과 시각",
    section: "2-3-1 여러 가지 모양 찾아보기",
    orderIndex: 39,
  },
  {
    grade: "초1",
    chapter: "2-3 모양과 시각",
    section: "2-3-2 여러 가지 모양으로 꾸미기",
    orderIndex: 40,
  },
  {
    grade: "초1",
    chapter: "2-3 모양과 시각",
    section: "2-3-3 몇 시 알아보기",
    orderIndex: 41,
  },
  {
    grade: "초1",
    chapter: "2-3 모양과 시각",
    section: "2-3-4 몇 시 30분 알아보기",
    orderIndex: 42,
  },
  // ── 2-4 덧셈과 뺄셈(2) ──
  {
    grade: "초1",
    chapter: "2-4 덧셈과 뺄셈(2)",
    section: "2-4-1 10을 이용하여 모으기와 가르기",
    orderIndex: 43,
  },
  {
    grade: "초1",
    chapter: "2-4 덧셈과 뺄셈(2)",
    section: "2-4-2 받아올림이 있는 (몇)+(몇)",
    orderIndex: 44,
  },
  {
    grade: "초1",
    chapter: "2-4 덧셈과 뺄셈(2)",
    section: "2-4-3 여러 가지 덧셈하기",
    orderIndex: 45,
  },
  {
    grade: "초1",
    chapter: "2-4 덧셈과 뺄셈(2)",
    section: "2-4-4 받아내림이 있는 (십몇)-(몇)",
    orderIndex: 46,
  },
  {
    grade: "초1",
    chapter: "2-4 덧셈과 뺄셈(2)",
    section: "2-4-5 여러 가지 뺄셈하기",
    orderIndex: 47,
  },
  // ── 2-5 규칙 찾기 ──
  {
    grade: "초1",
    chapter: "2-5 규칙 찾기",
    section: "2-5-1 규칙 찾기",
    orderIndex: 48,
  },
  {
    grade: "초1",
    chapter: "2-5 규칙 찾기",
    section: "2-5-2 규칙 만들기",
    orderIndex: 49,
  },
  {
    grade: "초1",
    chapter: "2-5 규칙 찾기",
    section: "2-5-3 수 배열에서 규칙 찾기",
    orderIndex: 50,
  },
  {
    grade: "초1",
    chapter: "2-5 규칙 찾기",
    section: "2-5-4 수 배열표에서 규칙 찾기",
    orderIndex: 51,
  },
  {
    grade: "초1",
    chapter: "2-5 규칙 찾기",
    section: "2-5-5 규칙을 여러 가지 방법으로 나타내기",
    orderIndex: 52,
  },
  // ── 2-6 덧셈과 뺄셈(3) ──
  {
    grade: "초1",
    chapter: "2-6 덧셈과 뺄셈(3)",
    section: "2-6-1 (몇십)+(몇), (몇십몇)+(몇)",
    orderIndex: 53,
  },
  {
    grade: "초1",
    chapter: "2-6 덧셈과 뺄셈(3)",
    section: "2-6-2 (몇십)+(몇십), (몇십몇)+(몇십몇)",
    orderIndex: 54,
  },
  {
    grade: "초1",
    chapter: "2-6 덧셈과 뺄셈(3)",
    section: "2-6-3 (몇십몇)-(몇), (몇십)-(몇십)",
    orderIndex: 55,
  },
  {
    grade: "초1",
    chapter: "2-6 덧셈과 뺄셈(3)",
    section: "2-6-4 (몇십몇)-(몇십몇)",
    orderIndex: 56,
  },
  {
    grade: "초1",
    chapter: "2-6 덧셈과 뺄셈(3)",
    section: "2-6-5 덧셈과 뺄셈 관계 알아보기",
    orderIndex: 57,
  },
  // ═════════ 초2 ═════════
  // ── 1-1 세 자리 수 ──
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-1 백 알아보기",
    orderIndex: 58,
  },
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-2 몇백 알아보기",
    orderIndex: 59,
  },
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-3 세 자리 수 알아보기",
    orderIndex: 60,
  },
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-4 세 자리 수의 각 자리 숫자가 나타내는 값",
    orderIndex: 61,
  },
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-5 세 자리 수 뛰어 세기",
    orderIndex: 62,
  },
  {
    grade: "초2",
    chapter: "1-1 세 자리 수",
    section: "1-1-6 세 자리 수의 크기 비교",
    orderIndex: 63,
  },
  // ── 1-2 여러 가지 도형 ──
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-1 원 알아보기",
    orderIndex: 64,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-2 삼각형 알아보기",
    orderIndex: 65,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-3 사각형 알아보기",
    orderIndex: 66,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-4 오각형과 육각형 알아보기",
    orderIndex: 67,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-5 칠교판으로 모양 만들기",
    orderIndex: 68,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-6 똑같은 모양으로 쌓기",
    orderIndex: 69,
  },
  {
    grade: "초2",
    chapter: "1-2 여러 가지 도형",
    section: "1-2-7 여러 가지 모양으로 쌓기",
    orderIndex: 70,
  },
  // ── 1-3 덧셈과 뺄셈 ──
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-1 받아올림이 있는 (두 자리 수)+(한 자리 수)",
    orderIndex: 71,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-2 받아올림이 한 번 있는 (두 자리 수)+(두 자리 수)",
    orderIndex: 72,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-3 받아올림이 두 번 있는 (두 자리 수)+(두 자리 수)",
    orderIndex: 73,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-4 여러 가지 방법으로 덧셈하기",
    orderIndex: 74,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-5 받아내림이 있는 (두 자리 수)-(한 자리 수)",
    orderIndex: 75,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-6 받아내림이 있는 (두 자리 수)-(두 자리 수)",
    orderIndex: 76,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-7 여러 가지 방법으로 뺄셈하기",
    orderIndex: 77,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-8 덧셈과 뺄셈의 관계를 식으로 나타내기",
    orderIndex: 78,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-9 □의 값 구하기",
    orderIndex: 79,
  },
  {
    grade: "초2",
    chapter: "1-3 덧셈과 뺄셈",
    section: "1-3-10 세 수의 계산",
    orderIndex: 80,
  },
  // ── 1-4 길이 재기 ──
  {
    grade: "초2",
    chapter: "1-4 길이 재기",
    section: "1-4-1 여러 가지 단위로 길이 재기",
    orderIndex: 81,
  },
  {
    grade: "초2",
    chapter: "1-4 길이 재기",
    section: "1-4-2 1cm 알아보기",
    orderIndex: 82,
  },
  {
    grade: "초2",
    chapter: "1-4 길이 재기",
    section: "1-4-3 자로 길이 재기",
    orderIndex: 83,
  },
  {
    grade: "초2",
    chapter: "1-4 길이 재기",
    section: "1-4-4 길이 어림하기",
    orderIndex: 84,
  },
  // ── 1-5 분류하기 ──
  {
    grade: "초2",
    chapter: "1-5 분류하기",
    section: "1-5-1 분류 기준 정하기",
    orderIndex: 85,
  },
  {
    grade: "초2",
    chapter: "1-5 분류하기",
    section: "1-5-2 기준에 따라 분류하기",
    orderIndex: 86,
  },
  {
    grade: "초2",
    chapter: "1-5 분류하기",
    section: "1-5-3 분류하여 세어 보기",
    orderIndex: 87,
  },
  {
    grade: "초2",
    chapter: "1-5 분류하기",
    section: "1-5-4 분류한 결과 말해 보기",
    orderIndex: 88,
  },
  // ── 1-6 곱셈 ──
  {
    grade: "초2",
    chapter: "1-6 곱셈",
    section: "1-6-1 여러 가지 방법으로 세어 보기",
    orderIndex: 89,
  },
  {
    grade: "초2",
    chapter: "1-6 곱셈",
    section: "1-6-2 묶어 세어 보기",
    orderIndex: 90,
  },
  {
    grade: "초2",
    chapter: "1-6 곱셈",
    section: "1-6-3 몇의 몇 배 알아보기",
    orderIndex: 91,
  },
  {
    grade: "초2",
    chapter: "1-6 곱셈",
    section: "1-6-4 곱셈식 알아보기",
    orderIndex: 92,
  },
  {
    grade: "초2",
    chapter: "1-6 곱셈",
    section: "1-6-5 곱셈식으로 나타내기",
    orderIndex: 93,
  },
  // ── 2-1 네 자리 수 ──
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-1 천 알아보기",
    orderIndex: 94,
  },
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-2 몇천 알아보기",
    orderIndex: 95,
  },
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-3 네 자리 수 알아보기",
    orderIndex: 96,
  },
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-4 네 자리 수의 각 자리 숫자가 나타내는 값",
    orderIndex: 97,
  },
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-5 네 자리 수 뛰어 세기",
    orderIndex: 98,
  },
  {
    grade: "초2",
    chapter: "2-1 네 자리 수",
    section: "2-1-6 네 자리 수의 크기 비교",
    orderIndex: 99,
  },
  // ── 2-2 곱셈구구 ──
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-1 2단 곱셈구구",
    orderIndex: 100,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-2 5단 곱셈구구",
    orderIndex: 101,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-3 3단, 6단 곱셈구구",
    orderIndex: 102,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-4 4단, 8단 곱셈구구",
    orderIndex: 103,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-5 7단 곱셈구구",
    orderIndex: 104,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-6 9단 곱셈구구",
    orderIndex: 105,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-7 1단 곱셈구구와 0의 곱",
    orderIndex: 106,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-8 곱셈표 만들기",
    orderIndex: 107,
  },
  {
    grade: "초2",
    chapter: "2-2 곱셈구구",
    section: "2-2-9 곱셈구구의 활용",
    orderIndex: 108,
  },
  // ── 2-3 길이 재기 ──
  {
    grade: "초2",
    chapter: "2-3 길이 재기",
    section: "2-3-1 cm보다 더 큰 단위 알아보기",
    orderIndex: 109,
  },
  {
    grade: "초2",
    chapter: "2-3 길이 재기",
    section: "2-3-2 자로 길이 재고 나타내기",
    orderIndex: 110,
  },
  {
    grade: "초2",
    chapter: "2-3 길이 재기",
    section: "2-3-3 길이의 합",
    orderIndex: 111,
  },
  {
    grade: "초2",
    chapter: "2-3 길이 재기",
    section: "2-3-4 길이의 차",
    orderIndex: 112,
  },
  {
    grade: "초2",
    chapter: "2-3 길이 재기",
    section: "2-3-5 길이 어림하고 재어 보기",
    orderIndex: 113,
  },
  // ── 2-4 시각과 시간 ──
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-1 몇 시 몇 분 알아보기 (1)",
    orderIndex: 114,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-2 몇 시 몇 분 알아보기 (2)",
    orderIndex: 115,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-3 여러 가지 방법으로 시각 읽기",
    orderIndex: 116,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-4 1시간 알아보기",
    orderIndex: 117,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-5 걸린 시간 알아보기",
    orderIndex: 118,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-6 하루의 시간 알아보기",
    orderIndex: 119,
  },
  {
    grade: "초2",
    chapter: "2-4 시각과 시간",
    section: "2-4-7 달력 알아보기",
    orderIndex: 120,
  },
  // ── 2-5 표와 그래프 ──
  {
    grade: "초2",
    chapter: "2-5 표와 그래프",
    section: "2-5-1 자료를 분류하여 표로 나타내기",
    orderIndex: 121,
  },
  {
    grade: "초2",
    chapter: "2-5 표와 그래프",
    section: "2-5-2 자료를 조사하여 표로 나타내기",
    orderIndex: 122,
  },
  {
    grade: "초2",
    chapter: "2-5 표와 그래프",
    section: "2-5-3 자료를 그래프로 나타내기",
    orderIndex: 123,
  },
  {
    grade: "초2",
    chapter: "2-5 표와 그래프",
    section: "2-5-4 표와 그래프의 내용 알아보기",
    orderIndex: 124,
  },
  {
    grade: "초2",
    chapter: "2-5 표와 그래프",
    section: "2-5-5 표와 그래프로 나타내기",
    orderIndex: 125,
  },
  // ── 2-6 규칙 찾기 ──
  {
    grade: "초2",
    chapter: "2-6 규칙 찾기",
    section: "2-6-1 무늬에서 규칙 찾기",
    orderIndex: 126,
  },
  {
    grade: "초2",
    chapter: "2-6 규칙 찾기",
    section: "2-6-2 쌓은 모양에서 규칙 찾기",
    orderIndex: 127,
  },
  {
    grade: "초2",
    chapter: "2-6 규칙 찾기",
    section: "2-6-3 덧셈표에서 규칙 찾기",
    orderIndex: 128,
  },
  {
    grade: "초2",
    chapter: "2-6 규칙 찾기",
    section: "2-6-4 곱셈표에서 규칙 찾기",
    orderIndex: 129,
  },
  {
    grade: "초2",
    chapter: "2-6 규칙 찾기",
    section: "2-6-5 생활에서 규칙 찾기",
    orderIndex: 130,
  },
  // ═════════ 초3 ═════════
  // ── 1-1 덧셈과 뺄셈 ──
  {
    grade: "초3",
    chapter: "1-1 덧셈과 뺄셈",
    section: "1-1-1 받아올림이 없는, 한 번 있는 (세 자리 수)+(세 자리 수)",
    orderIndex: 131,
  },
  {
    grade: "초3",
    chapter: "1-1 덧셈과 뺄셈",
    section: "1-1-2 받아올림이 두 번, 세 번 있는 (세 자리 수)+(세 자리 수)",
    orderIndex: 132,
  },
  {
    grade: "초3",
    chapter: "1-1 덧셈과 뺄셈",
    section: "1-1-3 받아내림이 없는, 한 번 있는 (세 자리 수)-(세 자리 수)",
    orderIndex: 133,
  },
  {
    grade: "초3",
    chapter: "1-1 덧셈과 뺄셈",
    section: "1-1-4 받아내림이 두 번 있는 (세 자리 수)-(세 자리 수)",
    orderIndex: 134,
  },
  // ── 1-2 평면도형 ──
  {
    grade: "초3",
    chapter: "1-2 평면도형",
    section: "1-2-1 선분, 반직선, 직선",
    orderIndex: 135,
  },
  {
    grade: "초3",
    chapter: "1-2 평면도형",
    section: "1-2-2 각, 직각 알아보기",
    orderIndex: 136,
  },
  {
    grade: "초3",
    chapter: "1-2 평면도형",
    section: "1-2-3 직각삼각형 알아보기",
    orderIndex: 137,
  },
  {
    grade: "초3",
    chapter: "1-2 평면도형",
    section: "1-2-4 직각삼각형 알아보기",
    orderIndex: 138,
  },
  {
    grade: "초3",
    chapter: "1-2 평면도형",
    section: "1-2-5 정사각형 알아보기",
    orderIndex: 139,
  },
  // ── 1-3 나눗셈 ──
  {
    grade: "초3",
    chapter: "1-3 나눗셈",
    section: "1-3-1 똑같이 나누기",
    orderIndex: 140,
  },
  {
    grade: "초3",
    chapter: "1-3 나눗셈",
    section: "1-3-2 곱셈과 나눗셈의 관계",
    orderIndex: 141,
  },
  {
    grade: "초3",
    chapter: "1-3 나눗셈",
    section: "1-3-3 나눗셈의 몫을 곱셈식으로 구하기",
    orderIndex: 142,
  },
  {
    grade: "초3",
    chapter: "1-3 나눗셈",
    section: "1-3-4 나눗셈의 몫을 곱셈구구로 구하기",
    orderIndex: 143,
  },
  // ── 1-4 곱셈 ──
  {
    grade: "초3",
    chapter: "1-4 곱셈",
    section: "1-4-1 (몇십)×(몇)",
    orderIndex: 144,
  },
  {
    grade: "초3",
    chapter: "1-4 곱셈",
    section: "1-4-2 올림이 없는 (몇십몇)×(몇)",
    orderIndex: 145,
  },
  {
    grade: "초3",
    chapter: "1-4 곱셈",
    section: "1-4-3 십의 자리에서 올림이 있는 (몇십몇)×(몇)",
    orderIndex: 146,
  },
  {
    grade: "초3",
    chapter: "1-4 곱셈",
    section: "1-4-4 일의 자리에서 올림이 있는 (몇십몇)×(몇)",
    orderIndex: 147,
  },
  {
    grade: "초3",
    chapter: "1-4 곱셈",
    section: "1-4-5 십의 자리와 일의 자리에서 올림이 있는 (몇십몇)×(몇)",
    orderIndex: 148,
  },
  // ── 1-5 길이와 시간 ──
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-1 1cm보다 작은 단위",
    orderIndex: 149,
  },
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-2 1m보다 큰 단위",
    orderIndex: 150,
  },
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-3 길이와 거리를 어림하고 재어 보기",
    orderIndex: 151,
  },
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-4 1분보다 작은 단위",
    orderIndex: 152,
  },
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-5 시간의 덧셈",
    orderIndex: 153,
  },
  {
    grade: "초3",
    chapter: "1-5 길이와 시간",
    section: "1-5-6 시간의 뺄셈",
    orderIndex: 154,
  },
  // ── 1-6 분수와 소수 ──
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-1 똑같이 나누기",
    orderIndex: 155,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-2 분수 알아보기(1)",
    orderIndex: 156,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-3 분수 알아보기(2)",
    orderIndex: 157,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-4 분모가 같은 분수의 크기 비교",
    orderIndex: 158,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-5 단위분수의 크기 비교",
    orderIndex: 159,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-6 소수 알아보기",
    orderIndex: 160,
  },
  {
    grade: "초3",
    chapter: "1-6 분수와 소수",
    section: "1-6-7 소수의 크기 비교",
    orderIndex: 161,
  },
  // ── 2-1 곱셈 ──
  {
    grade: "초3",
    chapter: "2-1 곱셈",
    section: "2-1-1 (세 자리 수)×(한 자리 수) (1)",
    orderIndex: 162,
  },
  {
    grade: "초3",
    chapter: "2-1 곱셈",
    section: "2-1-2 (세 자리 수)×(한 자리 수) (2)",
    orderIndex: 163,
  },
  {
    grade: "초3",
    chapter: "2-1 곱셈",
    section: "2-1-3 (몇십)×(몇십), (몇십몇)×(몇십), (몇)×(몇십몇)",
    orderIndex: 164,
  },
  {
    grade: "초3",
    chapter: "2-1 곱셈",
    section: "2-1-4 (몇십몇)×(몇십몇)",
    orderIndex: 165,
  },
  // ── 2-2 나눗셈 ──
  {
    grade: "초3",
    chapter: "2-2 나눗셈",
    section: "2-2-1 내림이 없는 (몇십)÷(몇), (몇십몇)÷(몇)",
    orderIndex: 166,
  },
  {
    grade: "초3",
    chapter: "2-2 나눗셈",
    section: "2-2-2 내림이 있는 (몇십)÷(몇), (몇십몇)÷(몇)",
    orderIndex: 167,
  },
  {
    grade: "초3",
    chapter: "2-2 나눗셈",
    section: "2-2-3 나머지가 있는 (몇십몇)÷(몇)",
    orderIndex: 168,
  },
  {
    grade: "초3",
    chapter: "2-2 나눗셈",
    section: "2-2-4 (세 자리 수)÷(한 자리 수)",
    orderIndex: 169,
  },
  // ── 2-3 원 ──
  {
    grade: "초3",
    chapter: "2-3 원",
    section: "2-3-1 원의 중심, 지름, 반지름",
    orderIndex: 170,
  },
  {
    grade: "초3",
    chapter: "2-3 원",
    section: "2-3-2 원의 성질",
    orderIndex: 171,
  },
  {
    grade: "초3",
    chapter: "2-3 원",
    section: "2-3-3 원 그리기",
    orderIndex: 172,
  },
  // ── 2-4 분수 ──
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-1 분수로 나타내기",
    orderIndex: 173,
  },
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-2 분수만큼은 얼마인지 알아보기 (1)",
    orderIndex: 174,
  },
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-3 분수만큼은 얼마인지 알아보기 (2)",
    orderIndex: 175,
  },
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-4 진분수와 가분수 알아보기",
    orderIndex: 176,
  },
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-5 대분수 알아보기",
    orderIndex: 177,
  },
  {
    grade: "초3",
    chapter: "2-4 분수",
    section: "2-4-6 분모가 같은 분수의 크기 비교",
    orderIndex: 178,
  },
  // ── 2-5 들이와 무게 ──
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-1 들이 비교하기",
    orderIndex: 179,
  },
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-2 들이의 단위",
    orderIndex: 180,
  },
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-3 들이의 합과 차",
    orderIndex: 181,
  },
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-4 무게 비교하기",
    orderIndex: 182,
  },
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-5 무게의 단위",
    orderIndex: 183,
  },
  {
    grade: "초3",
    chapter: "2-5 들이와 무게",
    section: "2-5-6 무게의 합과 차",
    orderIndex: 184,
  },
  // ── 2-6 그림그래프 ──
  {
    grade: "초3",
    chapter: "2-6 그림그래프",
    section: "2-6-1 그림그래프 알아보기",
    orderIndex: 185,
  },
  {
    grade: "초3",
    chapter: "2-6 그림그래프",
    section: "2-6-2 그림그래프로 나타내기",
    orderIndex: 186,
  },
  // ═════════ 초4 ═════════
  // ── 1-1 큰 수 ──
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-1 1000이 10개인 수 알아보기",
    orderIndex: 187,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-2 다섯 자리 수 알아보기",
    orderIndex: 188,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-3 10000이 몇십 개, 몇백 개, 몇천 개인 수 알아보기",
    orderIndex: 189,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-4 억 알아보기",
    orderIndex: 190,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-5 조 알아보기",
    orderIndex: 191,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-6 수 뛰어서 세기",
    orderIndex: 192,
  },
  {
    grade: "초4",
    chapter: "1-1 큰 수",
    section: "1-1-7 수의 크기 비교",
    orderIndex: 193,
  },
  // ── 1-2 각도 ──
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-1 각의 크기 비교하기",
    orderIndex: 194,
  },
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-2 각의 크기 재기",
    orderIndex: 195,
  },
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-3 각의 크기에 따라 분류하기",
    orderIndex: 196,
  },
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-4 각의 크기를 어림하고 각도의 합과 차 계산하기",
    orderIndex: 197,
  },
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-5 삼각형의 세 각의 크기의 합",
    orderIndex: 198,
  },
  {
    grade: "초4",
    chapter: "1-2 각도",
    section: "1-2-6 사각형의 네 각의 크기의 합 알아보기",
    orderIndex: 199,
  },
  // ── 1-3 곱셈과 나눗셈 ──
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-1 (세 자리 수)×(몇십)의 계산",
    orderIndex: 200,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-2 (세 자리 수)×(두 자리 수)의 계산",
    orderIndex: 201,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-3 곱셈의 어림셈",
    orderIndex: 202,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-4 몇십으로 나누기",
    orderIndex: 203,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-5 몇십몇으로 나누기 (1)",
    orderIndex: 204,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-6 몇십몇으로 나누기 (2)",
    orderIndex: 205,
  },
  {
    grade: "초4",
    chapter: "1-3 곱셈과 나눗셈",
    section: "1-3-7 나눗셈의 어림셈",
    orderIndex: 206,
  },
  // ── 1-4 평면도형의 이동 ──
  {
    grade: "초4",
    chapter: "1-4 평면도형의 이동",
    section: "1-4-1 점의 이동",
    orderIndex: 207,
  },
  {
    grade: "초4",
    chapter: "1-4 평면도형의 이동",
    section: "1-4-2 평면도형 밀기",
    orderIndex: 208,
  },
  {
    grade: "초4",
    chapter: "1-4 평면도형의 이동",
    section: "1-4-3 평면도형 뒤집기",
    orderIndex: 209,
  },
  {
    grade: "초4",
    chapter: "1-4 평면도형의 이동",
    section: "1-4-4 평면도형 돌리기",
    orderIndex: 210,
  },
  // ── 1-5 막대그래프 ──
  {
    grade: "초4",
    chapter: "1-5 막대그래프",
    section: "1-5-1 막대그래프 알아보기",
    orderIndex: 211,
  },
  {
    grade: "초4",
    chapter: "1-5 막대그래프",
    section: "1-5-2 막대그래프 그리기",
    orderIndex: 212,
  },
  {
    grade: "초4",
    chapter: "1-5 막대그래프",
    section: "1-5-3 막대그래프의 활용",
    orderIndex: 213,
  },
  // ── 1-6 규칙 찾기 ──
  {
    grade: "초4",
    chapter: "1-6 규칙 찾기",
    section: "1-6-1 수의 배열에서 규칙 찾기",
    orderIndex: 214,
  },
  {
    grade: "초4",
    chapter: "1-6 규칙 찾기",
    section: "1-6-2 도형의 배열에서 규칙 찾기",
    orderIndex: 215,
  },
  {
    grade: "초4",
    chapter: "1-6 규칙 찾기",
    section: "1-6-3 계산식에서 규칙 찾기",
    orderIndex: 216,
  },
  {
    grade: "초4",
    chapter: "1-6 규칙 찾기",
    section: "1-6-4 규칙적인 계산식 찾기",
    orderIndex: 217,
  },
  {
    grade: "초4",
    chapter: "1-6 규칙 찾기",
    section: "1-6-5 등호(=)를 사용하여 나타내기",
    orderIndex: 218,
  },
  // ── 2-1 분수의 덧셈과 뺄셈 ──
  {
    grade: "초4",
    chapter: "2-1 분수의 덧셈과 뺄셈",
    section: "2-1-1 진분수의 덧셈",
    orderIndex: 219,
  },
  {
    grade: "초4",
    chapter: "2-1 분수의 덧셈과 뺄셈",
    section: "2-1-2 진분수의 뺄셈",
    orderIndex: 220,
  },
  {
    grade: "초4",
    chapter: "2-1 분수의 덧셈과 뺄셈",
    section: "2-1-3 대분수의 덧셈",
    orderIndex: 221,
  },
  {
    grade: "초4",
    chapter: "2-1 분수의 덧셈과 뺄셈",
    section: "2-1-4 대분수의 뺄셈",
    orderIndex: 222,
  },
  // ── 2-2 삼각형 ──
  {
    grade: "초4",
    chapter: "2-2 삼각형",
    section: "2-2-1 삼각형을 변의 길이에 따라 분류하기",
    orderIndex: 223,
  },
  {
    grade: "초4",
    chapter: "2-2 삼각형",
    section: "2-2-2 이등변삼각형의 성질",
    orderIndex: 224,
  },
  {
    grade: "초4",
    chapter: "2-2 삼각형",
    section: "2-2-3 정삼각형의 성질",
    orderIndex: 225,
  },
  {
    grade: "초4",
    chapter: "2-2 삼각형",
    section: "2-2-4 삼각형을 각의 크기에 따라 분류하기",
    orderIndex: 226,
  },
  {
    grade: "초4",
    chapter: "2-2 삼각형",
    section: "2-2-5 삼각형을 두 가지 기준으로 분류하기",
    orderIndex: 227,
  },
  // ── 2-3 소수의 덧셈과 뺄셈 ──
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-1 소수 두 자리 수, 세 자리 수 알아보기",
    orderIndex: 228,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-2 소수의 크기 비교하기",
    orderIndex: 229,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-3 소수 사이의 관계",
    orderIndex: 230,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-4 소수 한 자리 수의 덧셈",
    orderIndex: 231,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-5 소수 한 자리 수의 뺄셈",
    orderIndex: 232,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-6 소수 두 자리 수의 덧셈",
    orderIndex: 233,
  },
  {
    grade: "초4",
    chapter: "2-3 소수의 덧셈과 뺄셈",
    section: "2-3-7 소수 두 자리 수의 뺄셈",
    orderIndex: 234,
  },
  // ── 2-4 사각형 ──
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-1 수직과 수선",
    orderIndex: 235,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-2 평행과 평행선",
    orderIndex: 236,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-3 평행선 사이의 거리",
    orderIndex: 237,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-4 사다리꼴",
    orderIndex: 238,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-5 평행사변형",
    orderIndex: 239,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-6 마름모",
    orderIndex: 240,
  },
  {
    grade: "초4",
    chapter: "2-4 사각형",
    section: "2-4-7 여러 가지 사각형",
    orderIndex: 241,
  },
  // ── 2-5 꺾은선그래프 ──
  {
    grade: "초4",
    chapter: "2-5 꺾은선그래프",
    section: "2-5-1 꺾은선그래프 알아보기",
    orderIndex: 242,
  },
  {
    grade: "초4",
    chapter: "2-5 꺾은선그래프",
    section: "2-5-2 꺾은선그래프 내용 알아보기",
    orderIndex: 243,
  },
  {
    grade: "초4",
    chapter: "2-5 꺾은선그래프",
    section: "2-5-3 꺾은선그래프 그리기와 활용하기",
    orderIndex: 244,
  },
  // ── 2-6 다각형 ──
  {
    grade: "초4",
    chapter: "2-6 다각형",
    section: "2-6-1 다각형",
    orderIndex: 245,
  },
  {
    grade: "초4",
    chapter: "2-6 다각형",
    section: "2-6-2 정다각형",
    orderIndex: 246,
  },
  {
    grade: "초4",
    chapter: "2-6 다각형",
    section: "2-6-3 대각선",
    orderIndex: 247,
  },
  {
    grade: "초4",
    chapter: "2-6 다각형",
    section: "2-6-4 모양 만들기와 채우기",
    orderIndex: 248,
  },
  // ═════════ 초5 ═════════
  // ── 1-1 자연수의 혼합 계산 ──
  {
    grade: "초5",
    chapter: "1-1 자연수의 혼합 계산",
    section: "1-1-1 덧셈과 뺄셈 / 곱셈과 나눗셈이 섞여 있는 식",
    orderIndex: 249,
  },
  {
    grade: "초5",
    chapter: "1-1 자연수의 혼합 계산",
    section: "1-1-2 덧셈, 뺄셈, 곱셈(나눗셈)이 섞여 있는 식",
    orderIndex: 250,
  },
  {
    grade: "초5",
    chapter: "1-1 자연수의 혼합 계산",
    section: "1-1-3 덧셈, 뺄셈, 곱셈, 나눗셈이 섞여 있는 식",
    orderIndex: 251,
  },
  // ── 1-2 약수와 배수 ──
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-1 약수와 배수",
    orderIndex: 252,
  },
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-2 약수와 배수의 관계",
    orderIndex: 253,
  },
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-3 공약수와 최대공약수",
    orderIndex: 254,
  },
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-4 최대공약수 구하는 방법",
    orderIndex: 255,
  },
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-5 공배수와 최소공배수",
    orderIndex: 256,
  },
  {
    grade: "초5",
    chapter: "1-2 약수와 배수",
    section: "1-2-6 최소공배수 구하는 방법",
    orderIndex: 257,
  },
  // ── 1-3 대응 관계 ──
  {
    grade: "초5",
    chapter: "1-3 대응 관계",
    section: "1-3-1 두 양 사이의 대응 관계",
    orderIndex: 258,
  },
  {
    grade: "초5",
    chapter: "1-3 대응 관계",
    section: "1-3-2 대응 관계를 식으로 나타내기",
    orderIndex: 259,
  },
  {
    grade: "초5",
    chapter: "1-3 대응 관계",
    section: "1-3-3 생활 속에서 대응 관계를 찾아 식으로 나타내기",
    orderIndex: 260,
  },
  // ── 1-4 약분과 통분 ──
  {
    grade: "초5",
    chapter: "1-4 약분과 통분",
    section: "1-4-1 크기가 같은 분수 알아보기",
    orderIndex: 261,
  },
  {
    grade: "초5",
    chapter: "1-4 약분과 통분",
    section: "1-4-2 분수를 간단하게 나타내기",
    orderIndex: 262,
  },
  {
    grade: "초5",
    chapter: "1-4 약분과 통분",
    section: "1-4-3 통분",
    orderIndex: 263,
  },
  {
    grade: "초5",
    chapter: "1-4 약분과 통분",
    section: "1-4-4 분수의 크기 비교",
    orderIndex: 264,
  },
  {
    grade: "초5",
    chapter: "1-4 약분과 통분",
    section: "1-4-5 분수와 소수의 크기 비교",
    orderIndex: 265,
  },
  // ── 1-5 분수의 덧셈과 뺄셈 ──
  {
    grade: "초5",
    chapter: "1-5 분수의 덧셈과 뺄셈",
    section: "1-5-1 진분수의 덧셈",
    orderIndex: 266,
  },
  {
    grade: "초5",
    chapter: "1-5 분수의 덧셈과 뺄셈",
    section: "1-5-2 대분수의 덧셈",
    orderIndex: 267,
  },
  {
    grade: "초5",
    chapter: "1-5 분수의 덧셈과 뺄셈",
    section: "1-5-3 진분수의 뺄셈",
    orderIndex: 268,
  },
  {
    grade: "초5",
    chapter: "1-5 분수의 덧셈과 뺄셈",
    section: "1-5-4 대분수의 뺄셈",
    orderIndex: 269,
  },
  // ── 1-6 다각형의 둘레와 넓이 ──
  {
    grade: "초5",
    chapter: "1-6 다각형의 둘레와 넓이",
    section: "1-6-1 정다각형과 사각형의 둘레",
    orderIndex: 270,
  },
  {
    grade: "초5",
    chapter: "1-6 다각형의 둘레와 넓이",
    section: "1-6-2 1cm², 직사각형과 정사각형의 넓이",
    orderIndex: 271,
  },
  {
    grade: "초5",
    chapter: "1-6 다각형의 둘레와 넓이",
    section: "1-6-3 1cm²보다 더 큰 넓이의 단위",
    orderIndex: 272,
  },
  {
    grade: "초5",
    chapter: "1-6 다각형의 둘레와 넓이",
    section: "1-6-4 평행사변형과 삼각형의 넓이",
    orderIndex: 273,
  },
  {
    grade: "초5",
    chapter: "1-6 다각형의 둘레와 넓이",
    section: "1-6-5 마름모와 사다리꼴의 넓이",
    orderIndex: 274,
  },
  // ── 2-1 수의 범위와 어림하기 ──
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-1 이상과 이하 알아보기",
    orderIndex: 275,
  },
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-2 초과와 미만 알아보기",
    orderIndex: 276,
  },
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-3 수의 범위를 알고 문제 해결하기",
    orderIndex: 277,
  },
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-4 올림 알아보기",
    orderIndex: 278,
  },
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-5 버림 알아보기",
    orderIndex: 279,
  },
  {
    grade: "초5",
    chapter: "2-1 수의 범위와 어림하기",
    section: "2-1-6 반올림 알아보기와 어림의 활용",
    orderIndex: 280,
  },
  // ── 2-2 분수의 곱셈 ──
  {
    grade: "초5",
    chapter: "2-2 분수의 곱셈",
    section: "2-2-1 (분수)×(자연수)의 계산",
    orderIndex: 281,
  },
  {
    grade: "초5",
    chapter: "2-2 분수의 곱셈",
    section: "2-2-2 (자연수)×(분수)의 계산",
    orderIndex: 282,
  },
  {
    grade: "초5",
    chapter: "2-2 분수의 곱셈",
    section: "2-2-3 진분수의 곱셈",
    orderIndex: 283,
  },
  {
    grade: "초5",
    chapter: "2-2 분수의 곱셈",
    section: "2-2-4 여러 가지 분수의 곱셈",
    orderIndex: 284,
  },
  // ── 2-3 합동과 대칭 ──
  {
    grade: "초5",
    chapter: "2-3 합동과 대칭",
    section: "2-3-1 도형의 합동 알아보기",
    orderIndex: 285,
  },
  {
    grade: "초5",
    chapter: "2-3 합동과 대칭",
    section: "2-3-2 합동인 도형의 성질 알아보기",
    orderIndex: 286,
  },
  {
    grade: "초5",
    chapter: "2-3 합동과 대칭",
    section: "2-3-3 선대칭도형과 그 성질 알아보기",
    orderIndex: 287,
  },
  {
    grade: "초5",
    chapter: "2-3 합동과 대칭",
    section: "2-3-4 점대칭도형과 그 성질 알아보기",
    orderIndex: 288,
  },
  // ── 2-4 소수의 곱셈 ──
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-1 (1보다 작은 소수)×(자연수)의 계산",
    orderIndex: 289,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-2 (1보다 큰 소수)×(자연수)의 계산",
    orderIndex: 290,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-3 (자연수)×(1보다 작은 소수)의 계산",
    orderIndex: 291,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-4 (자연수)×(1보다 큰 소수)의 계산",
    orderIndex: 292,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-5 (1보다 작은 소수)×(1보다 작은 소수)의 계산",
    orderIndex: 293,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-6 (1보다 큰 소수)×(1보다 큰 소수)의 계산",
    orderIndex: 294,
  },
  {
    grade: "초5",
    chapter: "2-4 소수의 곱셈",
    section: "2-4-7 곱의 소수점의 위치",
    orderIndex: 295,
  },
  // ── 2-5 직육면체 ──
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-1 직사각형 6개로 둘러싸인 도형",
    orderIndex: 296,
  },
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-2 정사각형 6개로 둘러싸인 도형",
    orderIndex: 297,
  },
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-3 직육면체의 성질",
    orderIndex: 298,
  },
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-4 직육면체의 겨냥도",
    orderIndex: 299,
  },
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-5 정육면체의 전개도",
    orderIndex: 300,
  },
  {
    grade: "초5",
    chapter: "2-5 직육면체",
    section: "2-5-6 직육면체의 전개도",
    orderIndex: 301,
  },
  // ── 2-6 평균과 가능성 ──
  {
    grade: "초5",
    chapter: "2-6 평균과 가능성",
    section: "2-6-1 평균 알아보기",
    orderIndex: 302,
  },
  {
    grade: "초5",
    chapter: "2-6 평균과 가능성",
    section: "2-6-2 평균을 이용하여 문제해결하기",
    orderIndex: 303,
  },
  {
    grade: "초5",
    chapter: "2-6 평균과 가능성",
    section: "2-6-3 일이 일어날 가능성",
    orderIndex: 304,
  },
  // ═════════ 초6 ═════════
  // ── 1-1 분수의 나눗셈 ──
  {
    grade: "초6",
    chapter: "1-1 분수의 나눗셈",
    section: "1-1-1 (자연수)÷(자연수)의 몫을 분수로 나타내기",
    orderIndex: 305,
  },
  {
    grade: "초6",
    chapter: "1-1 분수의 나눗셈",
    section: "1-1-2 (분수)÷(자연수) 알아보기",
    orderIndex: 306,
  },
  {
    grade: "초6",
    chapter: "1-1 분수의 나눗셈",
    section: "1-1-3 (대분수)÷(자연수) 알아보기",
    orderIndex: 307,
  },
  // ── 1-2 각기둥과 각뿔 ──
  {
    grade: "초6",
    chapter: "1-2 각기둥과 각뿔",
    section: "1-2-1 각기둥 알아보기와 각기둥의 밑면과 옆면",
    orderIndex: 308,
  },
  {
    grade: "초6",
    chapter: "1-2 각기둥과 각뿔",
    section: "1-2-2 각기둥의 이름과 구성 요소",
    orderIndex: 309,
  },
  {
    grade: "초6",
    chapter: "1-2 각기둥과 각뿔",
    section: "1-2-3 각기둥의 전개도",
    orderIndex: 310,
  },
  {
    grade: "초6",
    chapter: "1-2 각기둥과 각뿔",
    section: "1-2-4 각뿔 알아보기와 각뿔의 밑면과 옆면",
    orderIndex: 311,
  },
  {
    grade: "초6",
    chapter: "1-2 각기둥과 각뿔",
    section: "1-2-5 각뿔의 이름과 구성 요소",
    orderIndex: 312,
  },
  // ── 1-3 소수의 나눗셈 ──
  {
    grade: "초6",
    chapter: "1-3 소수의 나눗셈",
    section: "1-3-1 (소수)÷(자연수) 알아보기",
    orderIndex: 313,
  },
  {
    grade: "초6",
    chapter: "1-3 소수의 나눗셈",
    section: "1-3-2 몫이 1보다 작은 (소수)÷(자연수) 알아보기",
    orderIndex: 314,
  },
  {
    grade: "초6",
    chapter: "1-3 소수의 나눗셈",
    section: "1-3-3 소수점 아래 0을 내려 계산하는 (소수)÷(자연수) 알아보기",
    orderIndex: 315,
  },
  {
    grade: "초6",
    chapter: "1-3 소수의 나눗셈",
    section: "1-3-4 몫의 소수 첫째 자리에 0이 있는 (소수)÷(자연수) 알아보기",
    orderIndex: 316,
  },
  {
    grade: "초6",
    chapter: "1-3 소수의 나눗셈",
    section: "1-3-5 (자연수)÷(자연수), 어림셈하여 몫의 소수점 위치 확인하기",
    orderIndex: 317,
  },
  // ── 1-4 비와 비율 ──
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-1 두 수 비교하기",
    orderIndex: 318,
  },
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-2 비",
    orderIndex: 319,
  },
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-3 비율",
    orderIndex: 320,
  },
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-4 비율이 사용되는 경우",
    orderIndex: 321,
  },
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-5 백분율",
    orderIndex: 322,
  },
  {
    grade: "초6",
    chapter: "1-4 비와 비율",
    section: "1-4-6 백분율이 사용되는 경우",
    orderIndex: 323,
  },
  // ── 1-5 여러 가지 그래프 ──
  {
    grade: "초6",
    chapter: "1-5 여러 가지 그래프",
    section: "1-5-1 띠그래프",
    orderIndex: 324,
  },
  {
    grade: "초6",
    chapter: "1-5 여러 가지 그래프",
    section: "1-5-2 띠그래프로 나타내기",
    orderIndex: 325,
  },
  {
    grade: "초6",
    chapter: "1-5 여러 가지 그래프",
    section: "1-5-3 원그래프",
    orderIndex: 326,
  },
  {
    grade: "초6",
    chapter: "1-5 여러 가지 그래프",
    section: "1-5-4 원그래프로 나타내기",
    orderIndex: 327,
  },
  {
    grade: "초6",
    chapter: "1-5 여러 가지 그래프",
    section: "1-5-5 여러 가지 그래프 비교하기",
    orderIndex: 328,
  },
  // ── 1-6 직육면체의 겉넓이와 부피 ──
  {
    grade: "초6",
    chapter: "1-6 직육면체의 겉넓이와 부피",
    section: "1-6-1 직육면체의 겉넓이 구하는 방법",
    orderIndex: 329,
  },
  {
    grade: "초6",
    chapter: "1-6 직육면체의 겉넓이와 부피",
    section: "1-6-2 직육면체의 부피 비교와 직육면체의 부피 구하는 방법",
    orderIndex: 330,
  },
  {
    grade: "초6",
    chapter: "1-6 직육면체의 겉넓이와 부피",
    section: "1-6-3 ㎥ 알아보기",
    orderIndex: 331,
  },
  // ── 2-1 분수의 나눗셈 ──
  {
    grade: "초6",
    chapter: "2-1 분수의 나눗셈",
    section: "2-1-1 분모가 같은 (분수)÷(분수) 알아보기",
    orderIndex: 332,
  },
  {
    grade: "초6",
    chapter: "2-1 분수의 나눗셈",
    section: "2-1-2 분모가 다른 (분수)÷(분수) 알아보기",
    orderIndex: 333,
  },
  {
    grade: "초6",
    chapter: "2-1 분수의 나눗셈",
    section: "2-1-3 (자연수)÷(분수) 알아보기",
    orderIndex: 334,
  },
  {
    grade: "초6",
    chapter: "2-1 분수의 나눗셈",
    section: "2-1-4 (분수)÷(분수)를 (분수)×(분수)로 나타내기",
    orderIndex: 335,
  },
  {
    grade: "초6",
    chapter: "2-1 분수의 나눗셈",
    section: "2-1-5 (가분수)÷(분수), (대분수)÷(분수) 알아보기",
    orderIndex: 336,
  },
  // ── 2-2 소수의 나눗셈 ──
  {
    grade: "초6",
    chapter: "2-2 소수의 나눗셈",
    section: "2-2-1 자릿수가 같은 (소수)÷(소수) 알아보기",
    orderIndex: 337,
  },
  {
    grade: "초6",
    chapter: "2-2 소수의 나눗셈",
    section: "2-2-2 자릿수가 다른 (소수)÷(소수) 알아보기",
    orderIndex: 338,
  },
  {
    grade: "초6",
    chapter: "2-2 소수의 나눗셈",
    section: "2-2-3 (자연수)÷(소수) 알아보기",
    orderIndex: 339,
  },
  {
    grade: "초6",
    chapter: "2-2 소수의 나눗셈",
    section: "2-2-4 몫을 반올림하여 나타내기",
    orderIndex: 340,
  },
  {
    grade: "초6",
    chapter: "2-2 소수의 나눗셈",
    section: "2-2-5 나누어 주고 남는 양 알아보기",
    orderIndex: 341,
  },
  // ── 2-3 공간과 입체 ──
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-1 어느 방향에서 보았는지 알아보기",
    orderIndex: 342,
  },
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-2 쌓은 모양과 쌓기나무의 개수 알아보기 (1)",
    orderIndex: 343,
  },
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-3 쌓은 모양과 쌓기나무의 개수 알아보기 (2)",
    orderIndex: 344,
  },
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-4 쌓은 모양과 쌓기나무의 개수 알아보기 (3)",
    orderIndex: 345,
  },
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-5 쌓은 모양과 쌓기나무의 개수 알아보기 (4)",
    orderIndex: 346,
  },
  {
    grade: "초6",
    chapter: "2-3 공간과 입체",
    section: "2-3-6 여러 가지 모양 만들기",
    orderIndex: 347,
  },
  // ── 2-4 비례식과 비례배분 ──
  {
    grade: "초6",
    chapter: "2-4 비례식과 비례배분",
    section: "2-4-1 비의 성질 알아보기",
    orderIndex: 348,
  },
  {
    grade: "초6",
    chapter: "2-4 비례식과 비례배분",
    section: "2-4-2 간단한 자연수의 비로 나타내기",
    orderIndex: 349,
  },
  {
    grade: "초6",
    chapter: "2-4 비례식과 비례배분",
    section: "2-4-3 비례식 알아보기",
    orderIndex: 350,
  },
  {
    grade: "초6",
    chapter: "2-4 비례식과 비례배분",
    section: "2-4-4 비례식의 성질 알아보기",
    orderIndex: 351,
  },
  {
    grade: "초6",
    chapter: "2-4 비례식과 비례배분",
    section: "2-4-5 비례배분",
    orderIndex: 352,
  },
  // ── 2-5 원의 둘레와 넓이 ──
  {
    grade: "초6",
    chapter: "2-5 원의 둘레와 넓이",
    section: "2-5-1 원주와 원주율 알아보기",
    orderIndex: 353,
  },
  {
    grade: "초6",
    chapter: "2-5 원의 둘레와 넓이",
    section: "2-5-2 원주와 지름 구하기",
    orderIndex: 354,
  },
  {
    grade: "초6",
    chapter: "2-5 원의 둘레와 넓이",
    section: "2-5-3 원의 넓이 어림하기",
    orderIndex: 355,
  },
  {
    grade: "초6",
    chapter: "2-5 원의 둘레와 넓이",
    section: "2-5-4 원의 넓이 구하는 방법 알아보기",
    orderIndex: 356,
  },
  // ── 2-6 원기둥, 원뿔, 구 ──
  {
    grade: "초6",
    chapter: "2-6 원기둥, 원뿔, 구",
    section: "2-6-1 원기둥 알아보기",
    orderIndex: 357,
  },
  {
    grade: "초6",
    chapter: "2-6 원기둥, 원뿔, 구",
    section: "2-6-2 원기둥의 전개도 알아보기",
    orderIndex: 358,
  },
  {
    grade: "초6",
    chapter: "2-6 원기둥, 원뿔, 구",
    section: "2-6-3 원뿔 알아보기",
    orderIndex: 359,
  },
  {
    grade: "초6",
    chapter: "2-6 원기둥, 원뿔, 구",
    section: "2-6-4 구 알아보기와 여러 가지 모양 만들기",
    orderIndex: 360,
  },
  // ═════════ 중1 ═════════
  // ── 1. 소인수분해 ──
  {
    grade: "중1",
    chapter: "1. 소인수분해",
    section: "소수와 거듭제곱",
    orderIndex: 361,
  },
  {
    grade: "중1",
    chapter: "1. 소인수분해",
    section: "소인수분해",
    orderIndex: 362,
  },
  {
    grade: "중1",
    chapter: "1. 소인수분해",
    section: "공약수와 최대공약수",
    orderIndex: 363,
  },
  {
    grade: "중1",
    chapter: "1. 소인수분해",
    section: "공배수와 최소공배수",
    orderIndex: 364,
  },
  {
    grade: "중1",
    chapter: "1. 소인수분해",
    section: "최대공약수와 최소공배수의 활용",
    orderIndex: 365,
  },
  // ── 2. 정수와 유리수 ──
  {
    grade: "중1",
    chapter: "2. 정수와 유리수",
    section: "정수와 유리수",
    orderIndex: 366,
  },
  {
    grade: "중1",
    chapter: "2. 정수와 유리수",
    section: "수의 대소관계",
    orderIndex: 367,
  },
  {
    grade: "중1",
    chapter: "2. 정수와 유리수",
    section: "유리수의 덧셈과 뺄셈",
    orderIndex: 368,
  },
  {
    grade: "중1",
    chapter: "2. 정수와 유리수",
    section: "유리수의 곱셈",
    orderIndex: 369,
  },
  {
    grade: "중1",
    chapter: "2. 정수와 유리수",
    section: "유리수의 나눗셈",
    orderIndex: 370,
  },
  // ── 3. 방정식 ──
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "문자의 사용과 식의 값",
    orderIndex: 371,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차식의 뜻Ⅰ",
    orderIndex: 372,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차식의 뜻Ⅱ",
    orderIndex: 373,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "방정식과 그 해",
    orderIndex: 374,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "등식의 성질",
    orderIndex: 375,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 풀이",
    orderIndex: 376,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(해의 응용)",
    orderIndex: 377,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(수)",
    orderIndex: 378,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(나이, 과부족, 예금)",
    orderIndex: 379,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(증가와 감소, 원가와 정가)",
    orderIndex: 380,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(거리, 속력, 시간)",
    orderIndex: 381,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(도형, 농도, 일)",
    orderIndex: 382,
  },
  {
    grade: "중1",
    chapter: "3. 방정식",
    section: "일차방정식의 활용(비율, 시계, 규칙)",
    orderIndex: 383,
  },
  // ── 4. 그래프와 비례 ──
  {
    grade: "중1",
    chapter: "4. 그래프와 비례",
    section: "순서쌍과 좌표평면(기본)",
    orderIndex: 384,
  },
  {
    grade: "중1",
    chapter: "4. 그래프와 비례",
    section: "순서쌍과 좌표평면(응용)",
    orderIndex: 385,
  },
  {
    grade: "중1",
    chapter: "4. 그래프와 비례",
    section: "그래프의 이해",
    orderIndex: 386,
  },
  {
    grade: "중1",
    chapter: "4. 그래프와 비례",
    section: "정비례 관계 y=ax의 그래프",
    orderIndex: 387,
  },
  {
    grade: "중1",
    chapter: "4. 그래프와 비례",
    section: "반비례 관계 y=a/x의 그래프",
    orderIndex: 388,
  },
  // ── 5. 기본 도형 ──
  {
    grade: "중1",
    chapter: "5. 기본 도형",
    section: "점, 선, 면",
    orderIndex: 389,
  },
  { grade: "중1", chapter: "5. 기본 도형", section: "각", orderIndex: 390 },
  {
    grade: "중1",
    chapter: "5. 기본 도형",
    section: "두 직선의 위치 관계",
    orderIndex: 391,
  },
  {
    grade: "중1",
    chapter: "5. 기본 도형",
    section: "공간에서 평면의 위치 관계",
    orderIndex: 392,
  },
  { grade: "중1", chapter: "5. 기본 도형", section: "평행선", orderIndex: 393 },
  { grade: "중1", chapter: "5. 기본 도형", section: "작도", orderIndex: 394 },
  { grade: "중1", chapter: "5. 기본 도형", section: "합동", orderIndex: 395 },
  // ── 6. 평면도형 ──
  { grade: "중1", chapter: "6. 평면도형", section: "다각형", orderIndex: 396 },
  {
    grade: "중1",
    chapter: "6. 평면도형",
    section: "삼각형의 내각과 외각",
    orderIndex: 397,
  },
  {
    grade: "중1",
    chapter: "6. 평면도형",
    section: "다각형의 내각과 외각",
    orderIndex: 398,
  },
  {
    grade: "중1",
    chapter: "6. 평면도형",
    section: "원과 부채꼴",
    orderIndex: 399,
  },
  {
    grade: "중1",
    chapter: "6. 평면도형",
    section: "부채꼴의 호의 길이와 넓이",
    orderIndex: 400,
  },
  // ── 7. 입체도형 ──
  { grade: "중1", chapter: "7. 입체도형", section: "다면체", orderIndex: 401 },
  {
    grade: "중1",
    chapter: "7. 입체도형",
    section: "정다면체",
    orderIndex: 402,
  },
  { grade: "중1", chapter: "7. 입체도형", section: "회전체", orderIndex: 403 },
  {
    grade: "중1",
    chapter: "7. 입체도형",
    section: "기둥의 겉넓이와 부피",
    orderIndex: 404,
  },
  {
    grade: "중1",
    chapter: "7. 입체도형",
    section: "뿔의 겉넓이와 부피",
    orderIndex: 405,
  },
  {
    grade: "중1",
    chapter: "7. 입체도형",
    section: "구의 겉넓이와 부피",
    orderIndex: 406,
  },
  // ── 8. 통계 ──
  { grade: "중1", chapter: "8. 통계", section: "대푯값", orderIndex: 407 },
  {
    grade: "중1",
    chapter: "8. 통계",
    section: "줄기와 잎 그림",
    orderIndex: 408,
  },
  { grade: "중1", chapter: "8. 통계", section: "도수분포표", orderIndex: 409 },
  { grade: "중1", chapter: "8. 통계", section: "히스토그램", orderIndex: 410 },
  {
    grade: "중1",
    chapter: "8. 통계",
    section: "도수분포다각형",
    orderIndex: 411,
  },
  { grade: "중1", chapter: "8. 통계", section: "상대도수", orderIndex: 412 },
  // ═════════ 중2 ═════════
  // ── 1. 수와 식 ──
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "유리수와 소수",
    orderIndex: 413,
  },
  { grade: "중2", chapter: "1. 수와 식", section: "순환소수", orderIndex: 414 },
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "순환소수의 분수 표현",
    orderIndex: 415,
  },
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "순환소수를 포함한 식의 계산",
    orderIndex: 416,
  },
  { grade: "중2", chapter: "1. 수와 식", section: "지수법칙", orderIndex: 417 },
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "단항식의 곱셈과 나눗셈",
    orderIndex: 418,
  },
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "다항식의 덧셈과 뺄셈",
    orderIndex: 419,
  },
  {
    grade: "중2",
    chapter: "1. 수와 식",
    section: "다항식의 곱셈과 나눗셈",
    orderIndex: 420,
  },
  // ── 2. 부등식 ──
  { grade: "중2", chapter: "2. 부등식", section: "부등식", orderIndex: 421 },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 풀이",
    orderIndex: 422,
  },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 응용",
    orderIndex: 423,
  },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 활용(수, 평균, 정가)",
    orderIndex: 424,
  },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 활용(개수, 예금액, 유리한 방법)",
    orderIndex: 425,
  },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 활용(속력, 도형, 기타)",
    orderIndex: 426,
  },
  {
    grade: "중2",
    chapter: "2. 부등식",
    section: "일차부등식의 활용(농도)",
    orderIndex: 427,
  },
  // ── 3. 방정식 ──
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "미지수가 2개인 연립일차방정식",
    orderIndex: 428,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 풀이",
    orderIndex: 429,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "여러 가지 연립방정식의 풀이",
    orderIndex: 430,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 풀이의 응용",
    orderIndex: 431,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "해가 특수한 연립방정식",
    orderIndex: 432,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 활용(수, 평균, 나이)",
    orderIndex: 433,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 활용(가격, 개수, 증감, 도형)",
    orderIndex: 434,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 활용(일, 속력)",
    orderIndex: 435,
  },
  {
    grade: "중2",
    chapter: "3. 방정식",
    section: "연립방정식의 활용(농도, 비율, 합금)",
    orderIndex: 436,
  },
  // ── 4. 함수 ──
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "함수와 함숫값",
    orderIndex: 437,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 그래프와 절편",
    orderIndex: 438,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 그래프와 기울기",
    orderIndex: 439,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 그래프의 성질",
    orderIndex: 440,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 식 구하기",
    orderIndex: 441,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 활용(온도, 길이)",
    orderIndex: 442,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 활용(속력, 도형, 기타)",
    orderIndex: 443,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수와 일차방정식",
    orderIndex: 444,
  },
  {
    grade: "중2",
    chapter: "4. 함수",
    section: "일차함수의 그래프와 연립방정식의 해",
    orderIndex: 445,
  },
  // ── 5. 도형의 성질 ──
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "이등변삼각형의 성질",
    orderIndex: 446,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "직각삼각형의 합동",
    orderIndex: 447,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "삼각형의 외심",
    orderIndex: 448,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "삼각형의 내심",
    orderIndex: 449,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "평행사변형의 성질",
    orderIndex: 450,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "평행사변형이 되는 조건",
    orderIndex: 451,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "직사각형, 마름모, 정사각형",
    orderIndex: 452,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "등변사다리꼴, 여러 가지 사각형",
    orderIndex: 453,
  },
  {
    grade: "중2",
    chapter: "5. 도형의 성질",
    section: "평행선과 삼각형의 넓이",
    orderIndex: 454,
  },
  // ── 6. 도형의 닮음 ──
  {
    grade: "중2",
    chapter: "6. 도형의 닮음",
    section: "닮은 도형",
    orderIndex: 455,
  },
  {
    grade: "중2",
    chapter: "6. 도형의 닮음",
    section: "삼각형의 닮음 조건",
    orderIndex: 456,
  },
  // ── 7. 닮음의 활용 ──
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "삼각형에서 평행선 사이의 선분의 길이의 비",
    orderIndex: 457,
  },
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "삼각형의 각의 이등분선",
    orderIndex: 458,
  },
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "평행선 사이의 선분의 길이의 비",
    orderIndex: 459,
  },
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "삼각형의 두 변의 중점을 연결한 선분",
    orderIndex: 460,
  },
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "삼각형의 무게중심",
    orderIndex: 461,
  },
  {
    grade: "중2",
    chapter: "7. 닮음의 활용",
    section: "닮은 도형의 넓이의 비와 부피의 비",
    orderIndex: 462,
  },
  // ── 8. 피타고라스 정리 ──
  {
    grade: "중2",
    chapter: "8. 피타고라스 정리",
    section: "피타고라스 정리",
    orderIndex: 463,
  },
  {
    grade: "중2",
    chapter: "8. 피타고라스 정리",
    section: "피타고라스 정리의 활용",
    orderIndex: 464,
  },
  // ── 9. 확률 ──
  { grade: "중2", chapter: "9. 확률", section: "경우의 수", orderIndex: 465 },
  {
    grade: "중2",
    chapter: "9. 확률",
    section: "여러 가지 경우의 수",
    orderIndex: 466,
  },
  {
    grade: "중2",
    chapter: "9. 확률",
    section: "확률의 뜻과 성질",
    orderIndex: 467,
  },
  { grade: "중2", chapter: "9. 확률", section: "확률의 계산", orderIndex: 468 },
  // ═════════ 중3 ═════════
  // ── 1. 실수와 그 계산 ──
  {
    grade: "중3",
    chapter: "1. 실수와 그 계산",
    section: "제곱근의 뜻과 성질",
    orderIndex: 469,
  },
  {
    grade: "중3",
    chapter: "1. 실수와 그 계산",
    section: "무리수와 실수",
    orderIndex: 470,
  },
  {
    grade: "중3",
    chapter: "1. 실수와 그 계산",
    section: "근호를 포함한 식의 계산",
    orderIndex: 471,
  },
  // ── 2. 다항식의 곱셈과 인수분해 ──
  {
    grade: "중3",
    chapter: "2. 다항식의 곱셈과 인수분해",
    section: "다항식의 곱셈",
    orderIndex: 472,
  },
  {
    grade: "중3",
    chapter: "2. 다항식의 곱셈과 인수분해",
    section: "인수분해",
    orderIndex: 473,
  },
  {
    grade: "중3",
    chapter: "2. 다항식의 곱셈과 인수분해",
    section: "인수분해의 응용",
    orderIndex: 474,
  },
  // ── 3. 이차방정식 ──
  {
    grade: "중3",
    chapter: "3. 이차방정식",
    section: "이차방정식의 풀이",
    orderIndex: 475,
  },
  {
    grade: "중3",
    chapter: "3. 이차방정식",
    section: "이차방정식의 근의 공식과 응용",
    orderIndex: 476,
  },
  {
    grade: "중3",
    chapter: "3. 이차방정식",
    section: "이차방정식의 활용",
    orderIndex: 477,
  },
  // ── 4. 이차함수 ──
  {
    grade: "중3",
    chapter: "4. 이차함수",
    section: "이차함수와 그래프",
    orderIndex: 478,
  },
  {
    grade: "중3",
    chapter: "4. 이차함수",
    section: "이차함수 y=ax^2+bx+c의 그래프",
    orderIndex: 479,
  },
  {
    grade: "중3",
    chapter: "4. 이차함수",
    section: "이차함수의 최댓값과 최솟값",
    orderIndex: 480,
  },
  // ── 5. 삼각비 ──
  {
    grade: "중3",
    chapter: "5. 삼각비",
    section: "삼각비의 뜻",
    orderIndex: 481,
  },
  {
    grade: "중3",
    chapter: "5. 삼각비",
    section: "삼각비의 값",
    orderIndex: 482,
  },
  {
    grade: "중3",
    chapter: "5. 삼각비",
    section: "삼각비의 활용",
    orderIndex: 483,
  },
  // ── 6. 원의 성질 ──
  {
    grade: "중3",
    chapter: "6. 원의 성질",
    section: "원과 현",
    orderIndex: 484,
  },
  {
    grade: "중3",
    chapter: "6. 원의 성질",
    section: "원의 접선",
    orderIndex: 485,
  },
  { grade: "중3", chapter: "6. 원의 성질", section: "원주각", orderIndex: 486 },
  {
    grade: "중3",
    chapter: "6. 원의 성질",
    section: "원주각의 활용",
    orderIndex: 487,
  },
  // ── 7. 통계 ──
  {
    grade: "중3",
    chapter: "7. 통계",
    section: "대푯값과 산포도",
    orderIndex: 488,
  },
  {
    grade: "중3",
    chapter: "7. 통계",
    section: "산점도와 상관관계",
    orderIndex: 489,
  },
  { grade: "중3", chapter: "7. 통계", section: "상자그림", orderIndex: 490 },
  // ═════════ 공통수학1 ═════════
  // ── 1. 다항식 ──
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "다항식의 덧셈과 뺄셈",
    orderIndex: 491,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "다항식의 곱셈",
    orderIndex: 492,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "곱셈공식",
    orderIndex: 493,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "곱셈공식의 변형",
    orderIndex: 494,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "다항식의 나눗셈(1)",
    orderIndex: 495,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "다항식의 나눗셈(2)",
    orderIndex: 496,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "항등식",
    orderIndex: 497,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "다항식의 나눗셈과 항등식",
    orderIndex: 498,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "나머지와 인수정리(1)",
    orderIndex: 499,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "나머지와 인수정리(2)",
    orderIndex: 500,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "인수분해",
    orderIndex: 501,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "복잡한 식의 인수분해(1)",
    orderIndex: 502,
  },
  {
    grade: "공통수학1",
    chapter: "1. 다항식",
    section: "복잡한 식의 인수분해(2)",
    orderIndex: 503,
  },
  // ── 2. 방정식과 부등식 ──
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "복소수",
    orderIndex: 504,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "복소수의 연산",
    orderIndex: 505,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "켤레복소수의 성질",
    orderIndex: 506,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "i의 거듭제곱",
    orderIndex: 507,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "음수의 제곱근",
    orderIndex: 508,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식",
    orderIndex: 509,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "절댓값(가우스) 기호를 포함한 방정식",
    orderIndex: 510,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식의 판별식",
    orderIndex: 511,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식의 근과 계수의 관계",
    orderIndex: 512,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식의 식 구하기",
    orderIndex: 513,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식과 이차함수의 관계",
    orderIndex: 514,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차함수의 최대·최소(1)",
    orderIndex: 515,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차함수의 최대·최소(2)",
    orderIndex: 516,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "삼차방정식과 사차방정식(1)",
    orderIndex: 517,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "삼차방정식과 사차방정식(2)",
    orderIndex: 518,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "삼차방정식의 근의 조건",
    orderIndex: 519,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "삼차방정식의 근과 계수의 관계",
    orderIndex: 520,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "허근의 성질 x³=1,x³=-1",
    orderIndex: 521,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "미지수가 2개인 연립이차방정식(1)",
    orderIndex: 522,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "미지수가 2개인 연립이차방정식(2)",
    orderIndex: 523,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "인수분해가 되지 않는 연립이차방정식",
    orderIndex: 524,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "부정방정식",
    orderIndex: 525,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "일차부등식, 연립일차부등식(1)",
    orderIndex: 526,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "연립일차부등식(2)",
    orderIndex: 527,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "절댓값 기호를 포함한 일차부등식",
    orderIndex: 528,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차부등식",
    orderIndex: 529,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "절댓값(가우스) 기호를 포함한 이차부등식",
    orderIndex: 530,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차부등식의 해의 조건",
    orderIndex: 531,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "제한된 범위에서 항상 성립하는 이차부등식",
    orderIndex: 532,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "연립이차부등식",
    orderIndex: 533,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식의 실근의 부호",
    orderIndex: 534,
  },
  {
    grade: "공통수학1",
    chapter: "2. 방정식과 부등식",
    section: "이차방정식의 실근의 위치",
    orderIndex: 535,
  },
  // ── 3. 경우의 수 ──
  {
    grade: "공통수학1",
    chapter: "3. 경우의 수",
    section: "경우의 수",
    orderIndex: 536,
  },
  {
    grade: "공통수학1",
    chapter: "3. 경우의 수",
    section: "순열",
    orderIndex: 537,
  },
  {
    grade: "공통수학1",
    chapter: "3. 경우의 수",
    section: "조합",
    orderIndex: 538,
  },
  {
    grade: "공통수학1",
    chapter: "3. 경우의 수",
    section: "조 나누기",
    orderIndex: 539,
  },
  // ── 4. 행렬 ──
  { grade: "공통수학1", chapter: "4. 행렬", section: "행렬", orderIndex: 540 },
  {
    grade: "공통수학1",
    chapter: "4. 행렬",
    section: "행렬의 덧셈, 뺄셈과 실수배",
    orderIndex: 541,
  },
  {
    grade: "공통수학1",
    chapter: "4. 행렬",
    section: "행렬의 곱셈",
    orderIndex: 542,
  },
  {
    grade: "공통수학1",
    chapter: "4. 행렬",
    section: "행렬의 곱셈의 성질",
    orderIndex: 543,
  },
  // ═════════ 공통수학2 ═════════
  // ── 1. 도형의 방정식 ──
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "두 점 사이의 거리(1)",
    orderIndex: 544,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "두 점 사이의 거리(2)",
    orderIndex: 545,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "선분의 내분점",
    orderIndex: 546,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "삼각형의 무게중심",
    orderIndex: 547,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "직선의 방정식",
    orderIndex: 548,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "두 직선의 교점을 지나는 직선의 방정식",
    orderIndex: 549,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "두 직선의 위치관계",
    orderIndex: 550,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "점과 직선 사이의 거리",
    orderIndex: 551,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "증명",
    orderIndex: 552,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "원의 방정식",
    orderIndex: 553,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "좌표축에 접하는 원의 방정식",
    orderIndex: 554,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "자취의 방정식",
    orderIndex: 555,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "두 원의 교점을 지나는 도형의 방정식",
    orderIndex: 556,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "(교육과정 외) 두 원의 위치 관계",
    orderIndex: 557,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "원과 직선의 위치 관계",
    orderIndex: 558,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "원의 접선의 방정식(1)",
    orderIndex: 559,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "원의 접선의 방정식(2)",
    orderIndex: 560,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "평행이동",
    orderIndex: 561,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "대칭이동",
    orderIndex: 562,
  },
  {
    grade: "공통수학2",
    chapter: "1. 도형의 방정식",
    section: "점과 직선에 대한 대칭이동",
    orderIndex: 563,
  },
  // ── 2. 집합과 명제 ──
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "집합의 뜻과 표현",
    orderIndex: 564,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "원소의 개수에 따른 집합의 분류",
    orderIndex: 565,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "집합 사이의 포함관계",
    orderIndex: 566,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "합집합과 교집합",
    orderIndex: 567,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "여집합과 차집합",
    orderIndex: 568,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "집합의 연산 법칙",
    orderIndex: 569,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "배수의 집합의 연산, 대칭차집합",
    orderIndex: 570,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "유한집합의 원소의 개수",
    orderIndex: 571,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "명제와 조건",
    orderIndex: 572,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "명제 p→q",
    orderIndex: 573,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "모든'이나 '어떤'을 포함한 명제",
    orderIndex: 574,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "명제의 역과 대우",
    orderIndex: 575,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "충분조건과 필요조건",
    orderIndex: 576,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "명제의 증명",
    orderIndex: 577,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "절대부등식",
    orderIndex: 578,
  },
  {
    grade: "공통수학2",
    chapter: "2. 집합과 명제",
    section: "산술기하평균, 코시-슈바르츠의 부등식",
    orderIndex: 579,
  },
  // ── 3. 함수와 그래프 ──
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "함수",
    orderIndex: 580,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "여러 가지 함수(1)",
    orderIndex: 581,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "여러 가지 함수(2)",
    orderIndex: 582,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "합성함수(1)",
    orderIndex: 583,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "합성함수(2)",
    orderIndex: 584,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "역함수(1)",
    orderIndex: 585,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "역함수(2)",
    orderIndex: 586,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "유리식(1)",
    orderIndex: 587,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "유리식(2)",
    orderIndex: 588,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "유리함수(1)",
    orderIndex: 589,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "유리함수(2)",
    orderIndex: 590,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "무리식",
    orderIndex: 591,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "무리함수(1)",
    orderIndex: 592,
  },
  {
    grade: "공통수학2",
    chapter: "3. 함수와 그래프",
    section: "무리함수(2)",
    orderIndex: 593,
  },
  // ═════════ 대수 ═════════
  // ── 1. 지수함수와 로그함수 ──
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "거듭제곱근의 뜻",
    orderIndex: 594,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "거듭제곱근의 성질과 계산",
    orderIndex: 595,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수의 확장",
    orderIndex: 596,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수법칙의 응용",
    orderIndex: 597,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그의 뜻",
    orderIndex: 598,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그의 성질(1)",
    orderIndex: 599,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그의 성질(2)",
    orderIndex: 600,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "상용로그",
    orderIndex: 601,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수함수의 뜻과 그래프",
    orderIndex: 602,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수함수의 최대최소",
    orderIndex: 603,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수방정식",
    orderIndex: 604,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "지수부등식",
    orderIndex: 605,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그함수의 뜻과 그래프",
    orderIndex: 606,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그함수의 최대최소",
    orderIndex: 607,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그방정식",
    orderIndex: 608,
  },
  {
    grade: "대수",
    chapter: "1. 지수함수와 로그함수",
    section: "로그부등식",
    orderIndex: 609,
  },
  // ── 2. 삼각함수 ──
  { grade: "대수", chapter: "2. 삼각함수", section: "일반각", orderIndex: 610 },
  { grade: "대수", chapter: "2. 삼각함수", section: "호도법", orderIndex: 611 },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수의 뜻과 부호",
    orderIndex: 612,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수 사이의 관계",
    orderIndex: 613,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수의 그래프(1)",
    orderIndex: 614,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수의 그래프(2)",
    orderIndex: 615,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수의 그래프(3)",
    orderIndex: 616,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "일반각에 대한 성질",
    orderIndex: 617,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각함수의 최대최소",
    orderIndex: 618,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각방정식",
    orderIndex: 619,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각부등식",
    orderIndex: 620,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "사인법칙과 코사인법칙",
    orderIndex: 621,
  },
  {
    grade: "대수",
    chapter: "2. 삼각함수",
    section: "삼각형과 사각형의 넓이",
    orderIndex: 622,
  },
  // ── 3. 수열 ──
  { grade: "대수", chapter: "3. 수열", section: "등차수열", orderIndex: 623 },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "등차수열의 합",
    orderIndex: 624,
  },
  { grade: "대수", chapter: "3. 수열", section: "등비수열", orderIndex: 625 },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "등비수열의 합",
    orderIndex: 626,
  },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "시그마의 뜻과 성질",
    orderIndex: 627,
  },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "자연수의 거듭제곱의 합",
    orderIndex: 628,
  },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "여러 가지 수열의 합",
    orderIndex: 629,
  },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "수열의 귀납적 정의",
    orderIndex: 630,
  },
  {
    grade: "대수",
    chapter: "3. 수열",
    section: "수학적 귀납법",
    orderIndex: 631,
  },
  // ═════════ 미적분1 ═════════
  // ── 1. 함수의 극한과 연속 ──
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "함수의 극한",
    orderIndex: 632,
  },
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "함수의 좌극한과 우극한",
    orderIndex: 633,
  },
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "함수의 극한값의 계산",
    orderIndex: 634,
  },
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "함수의 극한의 활용",
    orderIndex: 635,
  },
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "함수의 연속",
    orderIndex: 636,
  },
  {
    grade: "미적분1",
    chapter: "1. 함수의 극한과 연속",
    section: "연속함수의 성질",
    orderIndex: 637,
  },
  // ── 2. 미분 ──
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "미분계수",
    orderIndex: 638,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "도함수와 미분법(1)",
    orderIndex: 639,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "도함수와 미분법(2)",
    orderIndex: 640,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "접선의 방정식",
    orderIndex: 641,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "롤의 정리와 평균값 정리",
    orderIndex: 642,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "함수의 증가와 감소",
    orderIndex: 643,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "함수의 극대와 극소",
    orderIndex: 644,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "함수의 그래프",
    orderIndex: 645,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "도함수의 방정식에서의 활용",
    orderIndex: 646,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "도함수의 부등식에서의 활용",
    orderIndex: 647,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "속도와 가속도",
    orderIndex: 648,
  },
  {
    grade: "미적분1",
    chapter: "2. 미분",
    section: "시각에 대한 변화율",
    orderIndex: 649,
  },
  // ── 3. 적분 ──
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "부정적분의 뜻",
    orderIndex: 650,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "부정적분의 계산",
    orderIndex: 651,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 뜻",
    orderIndex: 652,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 계산과 성질",
    orderIndex: 653,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 여러 계산",
    orderIndex: 654,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분으로 정의된 함수",
    orderIndex: 655,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 활용_넓이(1)",
    orderIndex: 656,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 활용_넓이(2)",
    orderIndex: 657,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 활용_넓이(3)",
    orderIndex: 658,
  },
  {
    grade: "미적분1",
    chapter: "3. 적분",
    section: "정적분의 활용_속도와 거리",
    orderIndex: 659,
  },
  // ═════════ 확률과 통계 ═════════
  // ── 1. 경우의 수 ──
  {
    grade: "확률과 통계",
    chapter: "1. 경우의 수",
    section: "중복순열",
    orderIndex: 660,
  },
  {
    grade: "확률과 통계",
    chapter: "1. 경우의 수",
    section: "같은 것이 있는 순열",
    orderIndex: 661,
  },
  {
    grade: "확률과 통계",
    chapter: "1. 경우의 수",
    section: "중복조합",
    orderIndex: 662,
  },
  {
    grade: "확률과 통계",
    chapter: "1. 경우의 수",
    section: "이항정리",
    orderIndex: 663,
  },
  {
    grade: "확률과 통계",
    chapter: "1. 경우의 수",
    section: "이항계수의 성질",
    orderIndex: 664,
  },
  // ── 2. 확률 ──
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "시행과 사건",
    orderIndex: 665,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "확률의 뜻",
    orderIndex: 666,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "확률의 덧셈정리와 여사건의 확률",
    orderIndex: 667,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "조건부확률",
    orderIndex: 668,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "확률의 곱셈정리",
    orderIndex: 669,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "사건의 독립과 종속",
    orderIndex: 670,
  },
  {
    grade: "확률과 통계",
    chapter: "2. 확률",
    section: "독립시행의 확률",
    orderIndex: 671,
  },
  // ── 3. 통계 ──
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "확률변수와 확률분포",
    orderIndex: 672,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "이산확률변수",
    orderIndex: 673,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "연속확률변수",
    orderIndex: 674,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "이항분포",
    orderIndex: 675,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "정규분포",
    orderIndex: 676,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "모평균과 표본평균",
    orderIndex: 677,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "모평균의 추정",
    orderIndex: 678,
  },
  {
    grade: "확률과 통계",
    chapter: "3. 통계",
    section: "모비율의 추정",
    orderIndex: 679,
  },
  // ═════════ 기하 ═════════
  // ── 1. 이차곡선 ──
  { grade: "기하", chapter: "1. 이차곡선", section: "포물선", orderIndex: 680 },
  { grade: "기하", chapter: "1. 이차곡선", section: "타원", orderIndex: 681 },
  { grade: "기하", chapter: "1. 이차곡선", section: "쌍곡선", orderIndex: 682 },
  {
    grade: "기하",
    chapter: "1. 이차곡선",
    section: "이차곡선 종합",
    orderIndex: 683,
  },
  {
    grade: "기하",
    chapter: "1. 이차곡선",
    section: "포물선의 접선의 방정식",
    orderIndex: 684,
  },
  {
    grade: "기하",
    chapter: "1. 이차곡선",
    section: "타원의 접선의 방정식",
    orderIndex: 685,
  },
  {
    grade: "기하",
    chapter: "1. 이차곡선",
    section: "쌍곡선의 접선의 방정식",
    orderIndex: 686,
  },
  // ── 2. 공간도형과 공간좌표 ──
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "공간도형-위치관계(1)",
    orderIndex: 687,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "공간도형-위치관계(2)",
    orderIndex: 688,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "삼수선 정리",
    orderIndex: 689,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "정사영",
    orderIndex: 690,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "점의 좌표",
    orderIndex: 691,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "두 점 사이의 거리",
    orderIndex: 692,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "선분의 내분점",
    orderIndex: 693,
  },
  {
    grade: "기하",
    chapter: "2. 공간도형과 공간좌표",
    section: "구의 방정식",
    orderIndex: 694,
  },
  // ── 3. 벡터 ──
  { grade: "기하", chapter: "3. 벡터", section: "벡터", orderIndex: 695 },
  { grade: "기하", chapter: "3. 벡터", section: "공간벡터", orderIndex: 696 },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "벡터의 덧셈과 뺄셈",
    orderIndex: 697,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "벡터의 실수배",
    orderIndex: 698,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "공간벡터의 실수배",
    orderIndex: 699,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "평면벡터의 성분",
    orderIndex: 700,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "공간벡터의 성분",
    orderIndex: 701,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "평면벡터의 내적",
    orderIndex: 702,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "공간벡터의 내적",
    orderIndex: 703,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "평면의 방정식",
    orderIndex: 704,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "점과 평면 사이의 거리",
    orderIndex: 705,
  },
  {
    grade: "기하",
    chapter: "3. 벡터",
    section: "벡터를 이용한 구의 방정식",
    orderIndex: 706,
  },
  // ═════════ 미적분2 ═════════
  // ── 1. 수열의 극한 ──
  {
    grade: "미적분2",
    chapter: "1. 수열의 극한",
    section: "수열의 극한",
    orderIndex: 707,
  },
  {
    grade: "미적분2",
    chapter: "1. 수열의 극한",
    section: "등비수열의 극한",
    orderIndex: 708,
  },
  {
    grade: "미적분2",
    chapter: "1. 수열의 극한",
    section: "급수의 뜻과 계산",
    orderIndex: 709,
  },
  {
    grade: "미적분2",
    chapter: "1. 수열의 극한",
    section: "등비급수",
    orderIndex: 710,
  },
  // ── 2. 미분법 ──
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "지수·로그함수의 극한과 무리수 e",
    orderIndex: 711,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "지수·로그함수의 주요극한과 미분",
    orderIndex: 712,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "삼각함수의 덧셈정리",
    orderIndex: 713,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "삼각함수의 극한과 미분",
    orderIndex: 714,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "몫의 미분법",
    orderIndex: 715,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "합성함수의 미분법",
    orderIndex: 716,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "여러 가지 미분법",
    orderIndex: 717,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "로그미분법과 이계도함수",
    orderIndex: 718,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "접선의 방정식",
    orderIndex: 719,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "함수의 극대와 극소",
    orderIndex: 720,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "곡선의 오목과 볼록, 함수의 그래프",
    orderIndex: 721,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "함수의 최대와 최소",
    orderIndex: 722,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "방정식과 부등식에의 활용",
    orderIndex: 723,
  },
  {
    grade: "미적분2",
    chapter: "2. 미분법",
    section: "속도와 가속도",
    orderIndex: 724,
  },
  // ── 3. 적분법 ──
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "부정적분",
    orderIndex: 725,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "치환적분법",
    orderIndex: 726,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "부분적분법",
    orderIndex: 727,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "정적분의 계산",
    orderIndex: 728,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "치환/부분적분법을 이용한 정적분",
    orderIndex: 729,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "정적분으로 정의된 함수",
    orderIndex: 730,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "정적분과 급수의 합",
    orderIndex: 731,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "정적분과 넓이",
    orderIndex: 732,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "여러 가지 도형의 넓이",
    orderIndex: 733,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "입체도형의 부피",
    orderIndex: 734,
  },
  {
    grade: "미적분2",
    chapter: "3. 적분법",
    section: "속도와 거리",
    orderIndex: 735,
  },
];
